<template>
    <v-container fluid class="pa-0">
        <v-row no-gutters>
            <v-col cols="12" style="position: relative;">
                <v-img height="350" src="https://checkedspot.blob.core.windows.net/assets/privacypolicy.jpg" cover></v-img>
                <div class="mainHeading">
                    <h1 class="text-h1 font-weight-regular text-white">Privacy Policy</h1>
                </div>
            </v-col>
            <v-col cols="12" class="pa-16">
                <p>Last updated: June 12, 2023</p>
                <br />
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                    information when You use the Service and tells You about Your privacy rights and how the law protects
                    You.</p>
                <br />
                <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                    collection and use of information in accordance with this Privacy Policy.</p>
                <br />

                <h2 class="text-h5 text-sm-h4 font-weight-medium">Interpretation and Definitions</h2>
                <br />
                <h3 class="text-h6 text-sm-h5 font-weight-medium">Interpretation</h3>
                <br />
                <p>The words of which the initial letter is capitalized have meanings defined under the following
                    conditions. The following definitions shall have the same meaning regardless of whether they appear in
                    singular or in plural.</p>
                <br />

                <h3 class="text-h6 text-sm-h5 font-weight-medium">Definitions</h3>
                <br />
                <p>For the purposes of this Privacy Policy:</p>
                <br />
                <div class="definitionSection">
                    <ul>
                        <li><strong>Account</strong> means a unique account created for You to access our Service or parts
                            of our Service.</li>

                        <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this
                            Agreement) refers to Checkedspot, 1st floor - Above Queens Collection, Subhash Square - Hassan 573201</li>

                        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any
                            other device by a website, containing the details of Your browsing history on that website among
                            its many uses.</li>

                        <li><strong>Country</strong> refers to: West Bengal, India.</li>

                        <li><strong>Device</strong> means any device that can access the Service such as a computer, a
                            cellphone or a digital tablet.</li>

                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable
                            individual.</li>

                        <li><strong>Service</strong> refers to the Website.</li>

                        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on
                            behalf of the Company. It refers to third-party companies or individuals employed by the Company
                            to facilitate the Service, to provide the Service on behalf of the Company, to perform services
                            related to the Service or to assist the Company in analyzing how the Service is used.</li>

                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use
                            of the Service or from the Service infrastructure itself (for example, the duration of a page
                            visit).</li>

                        <li><strong>Website</strong> refers to Checkedspot, accessible from https://checkedspot.com/
                        </li>

                        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or
                            other legal entity on behalf of which such individual is accessing or using the Service, as
                            applicable.</li>
                    </ul>
                </div>
            </v-col>
        </v-row>

    </v-container>
</template>
  
<script lang="ts" setup>
</script>
  
<style scoped>
.mainHeading {
    position: absolute;
    background: linear-gradient(90deg, rgba(3, 3, 3, 0.5) 8%, rgba(3, 3, 3, 0.5) 87%);
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
}

.mainHeading>h1 {
    text-align: center;
    position: relative;
    top: 50%;
    transform: translateY(-50%);
}

.definitionSection>ul>li {
    padding-left: 20px;
    list-style: none;
}

.definitionSection>ul>li::before {
    content: '\2022';
    display: inline-block;
    width: 1.5em;
    margin-left: -1.5em;
    margin-bottom: 1em;
    font-size: 1.1rem;
}</style>