<template>
    <v-container class="py-16">
        <v-row no-gutters>
            <v-col cols="12" class="d-flex justify-center">
                <h1 class="text-h2 font-weight-medium"><span class="text-pink">Terms Of</span> Service</h1>
            </v-col>
            <v-col cols="12" class="pt-10">
                <p class="pb-4">Thank you for visiting Checked Spot Subscriptions.</p>
                <p class="pb-4">Please read these Terms of Service ("Terms") which set forth terms for your use of our services.</p>
                <v-row no-gutters>
                    <v-col class="d-flex flex-column mb-4">
                        <p>You can find other important and valuable information here:</p>
                        <RouterLink to="/aboutus">About Us</RouterLink>
                        <RouterLink to="/privacypolicy">Privacy Policy</RouterLink>
                    </v-col>
                </v-row>
                <p>By using our Website or other versions of Checked Spot, digital or otherwise, you ("User") agree to be bound by the following Terms. You can review the most current version of these Terms at any time at this page. The word "Websites" includes all subdomains of Checked Spot and any content, news services, other services, code, data, features or functionality made available, directly or indirectly, from or through these Websites.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">1. Accuracy</h2>
                <p>Checked Spot takes pride in being unbiased, accurate and objective. We set a high bar in fact-checking and verifying the accuracy of information and the placement thereof in the correct context. That said, we are a news service, and often work with short deadlines. Information and material provided is for general information usage and should not be relied upon for making important decisions, especially business or life decisions that may have risk and/or a financial impact. If you do so, you do so at your own risk. We invite you to inform us of any inaccuracies or errors. Please forward an explanation of the alleged error to <a href="">checkedspot.com</a> and we will follow up.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">2. Ownership, Marks and Trademarks</h2>
                <p class="pb-4">The information and materials available through Checked Spot are the property of Checked Spot (or its Partners) and may be protected by copyright, trademark, and other intellectual property laws. Under the Terms, "Partners" refers to all third-party companies, such as sponsors, advertisers and service providers, with which Checked Spot has an agreement or working relationship related to the production, sourcing or distribution of news.</p>
                <p>Users are granted a non-exclusive license to use the information and material on this Website for their personal, non-commercial use (including, where available, to email/share individual stories directly from this site or via social media). Users are also granted a license to print a limited number of copies of any publicly available information and material posted on our Website, as long as it remains for personal, non-commercial and non-litigious use. Users may not reproduce or distribute copies of any of the information materials on this Website in any form (including by email or other electronic means) for any other use, without the prior written consent of Checked Spot.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">3. Submitted Materials and Other Contributions</h2>
                <p class="pb-4">By submitting material or information to us, you are representing that you are the owner of the material or information, are making your submission with the express consent of the owner, and/or have firsthand exposure to the information of materials. You agree that Checked Spot may reproduce, modify, and distribute such information and materials as we deem appropriate via any medium and for any purpose. You also agree that we, including our Partners, may identify you as the author of any of your postings by name, email address or screen name, as we deem appropriate. We also reserve the right (but assume no obligation) to delete, move, or edit any postings that come to our attention that we consider unacceptable, irrelevant, or inappropriate, whether for legal or other reasons.</p>
                <p>Unless specifically requested, we do not solicit nor do we wish to receive any confidential, secret or proprietary information or other material from you through the Websites, by email or in any other way. Any and all comments, information, creative works, demos, ideas, suggestions, concepts, methods, systems, designs, plans, techniques or other materials submitted or sent by you to us via any medium (including, for example and without limitation, photos, audio, video, messages, text, files or other content which you submit or post to our chat rooms, message boards, comment sections and/or our blogs, social media pages or feeds, or send to us via email or U.S. mail) ("Submitted Materials") will be deemed not to be confidential or secret, and may be used by us in any manner consistent with these Terms of Use and the Privacy Policy. By submitting or sending Submitted Materials to us, you: (i) represent and warrant that the Submitted Materials are original to you, that no other party has any rights thereto, and that any "moral rights" in Submitted Materials have been waived, (ii) that such Submitted Materials comply with these Terms of Use, including without limitation Section 6 (Prohibited Uses), and (iii) you grant us and our affiliates a royalty-free, unrestricted, worldwide, perpetual, irrevocable, non-exclusive and fully transferable, assignable and sublicensable right and license to use, copy, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, display and incorporate in other works any Submitted Materials (in whole or part) in any form, media, or technology now known or later developed, for any lawful purpose, including without limitation for promotional and/or commercial purposes.</p>
                <p class="pb-4">Under no circumstances will Checked Spot be liable for any inaccuracy or defect in any Submitted Materials</p>
                <p class="pb-4">Without limiting the foregoing, you agree that if you choose to submit comments (e.g. a "letter to our editors" or an online review or comment) to us via any medium (including those noted above with respect to all Submitted Materials), we may publish these comments along with, at our sole discretion, your name, screen name and other information you have provided to us in our editorial publications in any form, media or technology now known or later developed. You hereby consent to this. We cannot be responsible for maintaining any Submitted Material that you provide to us, and we may delete or destroy any such Submitted Material at any time. You are solely responsible for creating backup copies of your Submitted Materials if you desire.</p>
                <p class="pb-4">In the cases where you provide Checked Spot information or material, you agree to indemnify, defend, and hold harmless Checked Spot, our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns, and employees harmless from any claim or demand, including reasonable attorneys' fees, made by any third-party due to or arising out of your breach of these Terms of Service.</p>
                <p>If you provide Checked Spot any feedback or suggestions regarding the Websites ("Feedback"), including without limitation ideas, concepts, know-how or techniques relating to the functionality or design of the Websites, you hereby assign to Checked Spot all rights in the Feedback and agree that Checked Spot shall have the right to use such Feedback and related information in any manner it deems appropriate. You agree that you will not submit any feedback that you consider to be confidential or proprietary, and Checked Spot will treat any such Feedback as non-confidential and non-proprietary.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">4. Editorial Control</h2>
                <p>Checked Spot will always honor the confidentiality of a source of information, if said source provided the information and requested that said information or source be kept confidential. Checked Spot always retains the right, but does not have an obligation, to review and/or use any and all Submitted Materials. We always retain the right to refuse to post or to remove any Submitted Materials, in whole or in part, and will have the sole discretion to determine if any material is objectionable or in violation of these Terms.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">5. Rights and Trademarks</h2>
                <p>Most of the companies mentioned by Checked Spot own numerous trademarks and other marks. Checked Spot does not in any way, nor will it in the future, seek to challenge or deliberately dilute any of these marks. Users do not acquire any ownership rights by downloading any material, copyrighted or otherwise, from or through the Websites. If you make other use of the Websites and information or material therein, except as otherwise provided above, you may violate copyright and other laws of the United States and/or other countries, as well as applicable state laws and may be subject to liability for such unauthorized use. For web posting, reprint, transcript or licensing requests for Checked Spot material, please send your request to <a href="">checkedspot.com</a>.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">6. Prohibited Uses</h2>
                <p class="pb-4">Users are prohibited from using the Websites or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
                <p class="pb-3">Any commercial or promotional distribution, publishing or exploitation of the Websites is strictly prohibited unless you have received the express prior written permission from authorized personnel of Checked Spot. Other than as expressly allowed herein, you may not download, post, display, publish, copy, reproduce, distribute, transmit, modify, perform, broadcast, transfer, create derivative works from, sell or otherwise exploit the Websites.</p>
                <p>You further agree that you may not alter, edit, delete, remove, otherwise change the meaning or appearance of, or repurpose any of the content, code, data, or other materials on or available through the Websites, including, without limitation, the alteration or removal of any trademarks, trade names, logos, service marks, or any other proprietary content or proprietary rights notices. You may furthermore make no claim to marks or trademarks that are not yours, and agree not to contest and incorrectly use marks or trademarks that are not yours.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">7. Links</h2>
                <p class="pb-4">You may establish a hypertext link to Checked Spot so long as the link does not state or imply any endorsement or sponsorship of your site by Checked Spot. Checked Spot remains objective and cannot endorse or sponsor any company. You may not, without the prior written permission of Checked Spot, frame or otherwise incorporate into another website or other service, any material, content, or intellectual property belonging to Checked Spot. Exceptions can be made by Checked Spot and include RSS-feed widgets and video players that provide an embed code via a share button.</p>
                <p>You are not permitted to link directly to any image hosted on the Websites or our services, such as using an "in-line" linking method to cause the image hosted by us to be displayed on another website. You agree not to download or use images hosted on the Websites on another website, for any purpose, including, without limitation, posting such images on another site. We reserve all rights under the law to insist that any link to the Websites be discontinued, and to revoke your right to link to the Websites from any other websites at any time upon written notice to you.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">8. Subscriptions</h2>
                <p class="pb-4">An individual subscription is for a single user only, and you are responsible for payment as well as the activity that occurs through your account. You agree to provide current, complete and accurate account information for all purchases made on our Website. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed. You are not allowed to share your account login credentials or give your login credentials to anyone else. We may cancel or suspend access to your account if in our sole determination it is being accessed by multiple users. Any offer for any product or service made on this Website is void where prohibited.</p>
                <p class="pb-4">Subscription fees will be billed at the beginning of your subscription and any subsequent renewal. Fees for monthly subscriptions are non-refundable; annual subscription refunds will be pro-rated based on the unused portion of your subscription. If you already have a subscription to Checked Spot, your subscription will renew automatically unless you terminate it or you notify Customer Service of your decision to terminate your subscription. Customer Service can be reached at 949-787-4130 or <a>subscriptions@realestatenews.com</a>. If your subscription is annual, you will receive a reminder of your renewal at least 30 days before billing takes place. You must cancel your subscription before it renews in order to avoid billing of subscription fees for the renewal term. If you want to use a different credit card or there is a change in credit card validity or expiration date, you can update your payment information through your account settings.</p>
                <p>You understand that your personal information (excluding credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks. Pricing for any of our products or Services are also subject to change without notice. We reserve the right at any time to modify or discontinue any Service (or any part or content thereof) without notice at any time. We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of said Service.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">9. Service</h2>
                <p>Checked Spot reserves the right, but we are not obligated, to limit providing information or news, or the sales of our products or services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. We reserve the right to discontinue providing news or any other product at any time. The failure by us to exercise or enforce any right or provision of these Terms shall not constitute a waiver of our right or provision. Any ambiguities in the interpretation of these Terms shall not be construed against the drafting party. These Terms and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of California.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">10. Limitation of Liability</h2>
                <p class="pb-4">While Checked Spot makes every effort to present neutral, accurate, and balanced views of the real estate industry and its participants, we provide no warranties with respect to the accuracy or completeness of the contents. Users are urged to consult proper counsel or other experts regarding any points of law, finance, technology, and business before proceeding with any legal action or other actions. References to companies, products, services, and websites do not constitute or imply endorsement and neither are any references or absence of references intended to harm, place at a disadvantage, or in any way affect any company or person.</p>
                <p>In no case shall Checked Spot, its parents, directors, officers, employees, and/or partners be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content or product posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">11. Unenforceable</h2>
                <p>In the event that any provision of the Terms in this Agreement are determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">12. Ownership</h2>
                <p>Checked Spot is owned by T3 Sixty LLC. For information about T3 Sixty, please visit our corporate website at www.t360.com. Our corporate offices are located at 999 Corporate Drive, Suite 170, Ladera Ranch, California, United States, 92694.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">13. Changes</h2>
                <p>Checked Spot reserves the right, at our sole discretion, to update, change or replace any part of these Terms by posting updates and changes to our Website. It is the User's responsibility to check our Website periodically for changes. Your continued use of or access to our Website or the Service following the posting of any changes to these Terms constitutes acceptance of those changes.</p>
            </v-col>
            <v-col cols="12" class="pt-6">
                <h2 class="pb-3">Contact Us</h2>
                <p>If you have questions about the Terms of Service, please <RouterLink to="/contactus">contact us</RouterLink>.</p>
            </v-col>


        </v-row>
    </v-container>
</template>

<script lang="ts" setup>

    import {RouterLink} from "vue-router"
</script>

<style scoped>
    a{
        color: rgb(86, 173, 255);
    }
</style>