export function initializePlotPost() {
    const plotObj = {
        ownerName: "",
        type: "",
        category: "",
        country: "India",
        state: "",
        city: "",
        locality: "",
        subLocality: "",
        googleMapLink: "",
        totalArea: 0,
        totalAreaUnit: "",
        propertyDimension: {
            length: 0,
            breadth: 0
        },
        floorAllowed: 0,
        isBoundaryWallExist: false,
        noOfOpenSide: 0,
        isConstructionDoneOnProperty: false,
        constructions: [],
        possessionBy: "",
        ownershipType: "",
        isFreehold: false,
        isVerified: false,
        approvedByAuthorities: [],
        cost: 0,
        costPerSqFt: 0,
        otherChargesIncluded: false,
        isNegotiable: false,
        description: "",
        images: [],
        videos: [],
        documents: [],
        maintenanceStaff: false,
        waterStorage: false,
        rainWaterHarvesting: false,
        vaastuComplaint: false,
        pool: false,
        park: false,
        club: false,
        mainRoad: false,
        // other: ?
        isInGatedSociety: false,
        isCornerProperty: false, // what is corner property
        propertyFacing: "",
        facingRoadWidth: 0,
        nearMetroStation: false,
        nearSchool: false,
        nearHospital: false,
        nearMarket: false,
        nearBusStand: false,
        nearRailwayStation: false,
        nearAirport: false,
        nearButStand: false,
        nearMall: false,
        nearHighway: false,
    }

    return sessionStorage.getItem('plotData') ? JSON.parse(sessionStorage.getItem('plotData')) : plotObj;
    // sessionStorage.setItem('plotData', JSON.stringify(plotObj));
}

export function initializeFlatPost() {
    const flatObj = {
        ownerName: "",
        type: "",
        category: "",
        country: "India",
        state: "",
        city: "",
        locality: "",
        subLocality: "",
        googleMapLink: "",
        totalArea: 0,
        totalAreaUnit: "",
        propertyDimension: {
            length: 0,
            breadth: 0
        },
        floorAllowed: 0,
        isBoundaryWallExist: false,
        noOfOpenSide: 0,
        isConstructionDoneOnProperty: false,
        constructions: [],
        possessionBy: "",
        ownershipType: "",
        isFreehold: false,
        isVerified: false,
        approvedByAuthorities: [],
        cost: 0,
        otherChargesIncluded: false,
        isNegotiable: false,
        description: "",
        images: [],
        videos: [],
        documents: [],
        maintenanceStaff: false,
        waterStorage: false,
        rainWaterHarvesting: false,
        vaastuComplaint: false,
        pool: false,
        park: false,
        club: false,
        mainRoad: false,
        // other: ?
        isInGatedSociety: false,
        isCornerProperty: false, // what is corner property
        propertyFacing: "",
        facingRoadWidth: 0,
        nearMetroStation: false,
        nearSchool: false,
        nearHospital: false,
        nearMarket: false,
        nearRailwayStation: false,
        nearAirport: false,
        nearButStand: false,
        nearMall: false,
        nearHighway: false,
    }

    return sessionStorage.getItem('flatData') ? JSON.parse(sessionStorage.getItem('flatData')) : flatObj;
    // sessionStorage.setItem('flatData', JSON.stringify(flatObj));
}

export function initializeFarmlandPost() {
    const farmlandObj = {
        ownerName: "",
        type: "",
        category: "",
        country: "India",
        state: "",
        city: "",
        locality: "",
        subLocality: "",
        googleMapLink: "",
        totalArea: 0,
        totalAreaUnit: "",
        propertyDimension: {
            length: 0,
            breadth: 0
        },
        floorAllowed: 0,
        isBoundaryWallExist: false,
        noOfOpenSide: 0,
        isConstructionDoneOnProperty: false,
        constructions: [],
        possessionBy: "",
        ownershipType: "",
        isFreehold: false,
        isVerified: false,
        approvedByAuthorities: [],
        cost: 0,
        otherChargesIncluded: false,
        isNegotiable: false,
        description: "",
        images: [],
        videos: [],
        documents: [],
        maintenanceStaff: false,
        waterStorage: false,
        rainWaterHarvesting: false,
        vaastuComplaint: false,
        pool: false,
        park: false,
        club: false,
        mainRoad: false,
        // other: ?
        isInGatedSociety: false,
        isCornerProperty: false, // what is corner property
        propertyFacing: "",
        facingRoadWidth: 0,
        nearMetroStation: false,
        nearSchool: false,
        nearHospital: false,
        nearMarket: false,
        nearRailwayStation: false,
        nearAirport: false,
        nearButStand: false,
        nearMall: false,
        nearHighway: false,
    }
    
    return sessionStorage.getItem('farmlandData') ? JSON.parse(sessionStorage.getItem('farmlandData')) : farmlandObj;
    // sessionStorage.setItem('farmlandData', JSON.stringify(farmlandObj));
}
