export function initializePlotPost() {
    const plotObj = {
        ownerName: "",
        status: "",
        category: "",
        type: "",
        country: "India",
        state: null,
        city: null,
        locality: null,
        subLocality: "",
        googleMapLink: "",
        totalArea: null,
        totalAreaUnit: "square feet",
        propertyDimension: {
            length: null,
            breadth: null
        },
        floorAllowed: null,
        isBoundaryWallExist: false,
        noOfOpenSide: "1",
        isConstructionDoneOnProperty: false,
        constructions: [],
        possessionBy: "",
        ownershipType: "",
        isFreehold: false,
        isVerifiedByCheckedSpot: false,
        approvedByAuthorities: [],
        cost: null,
        costPerSqft: null,
        otherChargesIncluded: false,
        isNegotiable: false,
        description: "",
        images: [],
        videos: [],
        documents: [],
        maintenanceStaff: false,
        waterStorage: false,
        rainWaterHarvesting: false,
        vaastuCompliant: false,
        pool: false,
        garden: false,
        club: false,
        mainRoad: false,
        // other: ?
        isInGatedSociety: false,
        isCornerProperty: false, // what is corner property
        propertyFacing: "",
        facingRoadWidth: null,
        facingRoadWidthUnit: 'feet',
        nearMetroStation: false,
        nearSchool: false,
        nearHospital: false,
        nearMarket: false,
        nearBusStand: false,
        nearRailwayStation: false,
        nearAirport: false,
        nearMall: false,
        nearHighway: false,
    }

    return sessionStorage.getItem('plotData') ? JSON.parse(sessionStorage.getItem('plotData')) : plotObj;
}

export function initializeFlatPost() {
    const flatObj = {
        ownerName: "",
        status: "",
        category: "",
        type: "",
        country: "India",
        state: null,
        city: null,
        locality: null,
        subLocality: "",
        googleMapLink: "",
        totalArea: null,
        builtupArea: null,
        carpetArea: null,
        totalAreaUnit: "square feet",
        builtupAreaUnit: "square feet",
        carpetAreaUnit: "square feet",
        bedrooms: null,
        bathrooms: null,
        kitchens: null,
        balconies: null,
        isReadyToMoveIn: false,
        underConstruction: false,
        propertyAge: '',
        possessionBy: '',
        ownershipType: "",
        isFreehold: false,
        isVerifiedByCheckedSpot: false,
        approvedByAuthorities: [],
        cost: null,
        costPerSqft: null,
        otherChargesIncluded: false,
        isNegotiable: false,
        description: "",
        images: [],
        videos: [],
        documents: [],
        otherRooms: [],
        furnishedStatus: "",
        parking: false,
        floors: null,
        floorNumber: null,
        maintenanceStaff: false,
        waterStorage: false,
        securityOrFireAlarm: false,
        visitorParking: false,
        vaastuCompliant: false,
        park: false,
        garden: false,
        intercomFacility: false,
        elevator: false,
        highCeilingHeight: false,
        falseCeilingLighting: false,
        gasPipeline: false,
        wifi: false,
        centralizedAirConditioning: false,
        waterPurifier: false,
        recentlyRenovated: false,
        privateGarden: false,
        naturalLight: false,
        airyRooms: false,
        spaciousInterior: false,
        seperateServentRoomEntry: false,
        wasteDisposal: false,
        openDrainageAround: false,
        rainWaterHarvesting: false,
        bankAttachedProperty: false,
        lowDenseSociety: false,
        municipalCorporationWaterSupply: false,
        borewell: false,
        twentyFourBySevenWater: false,
        pool: false,
        club: false,
        mainRoad: false,
        isInGatedSociety: false,
        isCornerProperty: false, // what is corner property
        isPetFriendly: false,
        isWheelchairFriendly: false,
        powerBackup: "",
        propertyFacing: "",
        facingRoadWidth: null,
        facingRoadWidthUnit: 'feet',
        flooringType: [],
        nearMetroStation: false,
        nearSchool: false,
        nearHospital: false,
        nearMarket: false,
        nearRailwayStation: false,
        nearAirport: false,
        nearBusStand: false,
        nearMall: false,
        nearHighway: false,

        // Furnished addons
        light: false,
        fan: false,
        ac: false,
        tv: false,
        bed: false,
        wardrobe: false,
        geyser: false,
        refrigerator: false,
        sofa: false,
        washingMachine: false,
        stove: false,
        microwave: false,
        modularKitchen: false,
        chimney: false,
        curtain: false,
        exhaustFan: false,
    }

    return sessionStorage.getItem('flatData') ? JSON.parse(sessionStorage.getItem('flatData')) : flatObj;
}

export function initializeFarmlandPost() {
    const farmlandObj = {
        ownerName: "",
        status: "",
        category: "",
        type: "",
        country: "India",
        state: null,
        city: null,
        locality: null,
        subLocality: "",
        googleMapLink: "",
        totalArea: null,
        builtupArea: null,
        carpetArea: null,
        totalAreaUnit: "square feet",
        builtupAreaUnit: "square feet",
        carpetAreaUnit: "square feet",
        bedrooms: null,
        bathrooms: null,
        kitchens: null,
        balconies: null,
        otherRooms: [],
        furnishedStatus: '',
        parking: '',
        floors: null,
        isReadyToMoveIn: false,
        underConstruction: false,
        propertyAge: '',
        possessionBy: '',
        ownershipType: '',
        isFreehold: false,
        isVerifiedByCheckedSpot: false,
        cost: null,
        costPerSqft: null,
        otherChargesIncluded: false,
        isNegotiable: false,
        description: "",
        images: [],
        videos: [],
        documents: [],
        maintenanceStaff: false,
        waterStorage: false,
        securityOrFireAlarm: false,
        visitorParking: false,
        vaastuCompliant: false,
        park: false,
        intercomFacility: false,
        securityGuard: false,
        seperateServentRoomEntry: false,
        wasteDisposal: false,
        openDrainageAround: false,
        rainWaterHarvesting: false,
        bankAttachedProperty: false,
        lowDenseSociety: false,
        gym: false,
        municipalCorporationWaterSupply: false,
        borewell: false,
        twentyFourBySevenWater: false,
        pool: false,
        garden: false,
        club: false,
        mainRoad: false,
        isInGatedSociety: false,
        isCornerProperty: false, // what is corner property
        isPetFriendly: false,
        isWheelchairFriendly: false,
        propertyFacing: "",
        powerBackup: "",
        highCeilingHeight: false,
        falseCeilingLighting: false,
        gasPipeline: false,
        wifi: false,
        centralizedAirConditioning: false,
        waterPurifier: false,
        recentlyRenovated: false,
        privateGarden: false,
        naturalLight: false,
        airyRooms: false,
        spaciousInterior: false,
        flooringType: [],
        facingRoadWidth: null,
        facingRoadWidthUnit: 'feet',
        nearMetroStation: false,
        nearSchool: false,
        nearHospital: false,
        nearMarket: false,
        nearRailwayStation: false,
        nearAirport: false,
        nearBusStand: false,
        nearMall: false,
        nearHighway: false,

        // Furnished addons
        light: false,
        fan: false,
        ac: false,
        tv: false,
        bed: false,
        wardrobe: false,
        geyser: false,
        refrigerator: false,
        sofa: false,
        washingMachine: false,
        stove: false,
        microwave: false,
        modularKitchen: false,
        chimney: false,
        curtain: false,
        exhaustFan: false,
    }

    return sessionStorage.getItem('farmlandData') ? JSON.parse(sessionStorage.getItem('farmlandData')) : farmlandObj;
}

